
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Frame frame1;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.HPaned hpaned1;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Entry AnimeEntry;
	
	private global::Gtk.Button addanime;
	
	private global::Gtk.HButtonBox hbuttonbox1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView AnimeListed;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Entry AddBotEntry;
	
	private global::Gtk.ToggleButton Addbot;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Entry dltime;
	
	private global::Gtk.Button dltimeset;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Entry Logging;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Entry settingsloc;
	
	private global::Gtk.Button OpenSettings;
	
	private global::Gtk.Button createsettingfile;
	
	private global::Gtk.Button Save;
	
	private global::Gtk.Label GtkLabel5;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("AADSetup");
		this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, ".\\animeicon.png"));
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 720;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.WidthRequest = 640;
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.WidthRequest = 640;
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 593;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(3));
		// Container child vbox1.Gtk.Box+BoxChild
		this.AnimeEntry = new global::Gtk.Entry ();
		this.AnimeEntry.CanFocus = true;
		this.AnimeEntry.Name = "AnimeEntry";
		this.AnimeEntry.Text = global::Mono.Unix.Catalog.GetString ("Horriblesubs animename 720p");
		this.AnimeEntry.IsEditable = true;
		this.AnimeEntry.InvisibleChar = '●';
		this.vbox1.Add (this.AnimeEntry);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.AnimeEntry]));
		w1.Position = 0;
		w1.Expand = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.addanime = new global::Gtk.Button ();
		this.addanime.CanFocus = true;
		this.addanime.Name = "addanime";
		this.addanime.UseUnderline = true;
		this.addanime.Label = global::Mono.Unix.Catalog.GetString ("Add Anime");
		this.vbox1.Add (this.addanime);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.addanime]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbuttonbox1 = new global::Gtk.HButtonBox ();
		this.hbuttonbox1.Name = "hbuttonbox1";
		this.vbox1.Add (this.hbuttonbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox1]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.VscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.AnimeListed = new global::Gtk.TextView ();
		this.AnimeListed.CanFocus = true;
		this.AnimeListed.Name = "AnimeListed";
		this.GtkScrolledWindow.Add (this.AnimeListed);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w5.Position = 3;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.AddBotEntry = new global::Gtk.Entry ();
		this.AddBotEntry.CanFocus = true;
		this.AddBotEntry.Name = "AddBotEntry";
		this.AddBotEntry.Text = global::Mono.Unix.Catalog.GetString ("NOT USEABLE YET!!!");
		this.AddBotEntry.IsEditable = true;
		this.AddBotEntry.InvisibleChar = '●';
		this.hbox1.Add (this.AddBotEntry);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.AddBotEntry]));
		w6.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Addbot = new global::Gtk.ToggleButton ();
		this.Addbot.CanFocus = true;
		this.Addbot.Name = "Addbot";
		this.Addbot.UseUnderline = true;
		this.Addbot.Label = global::Mono.Unix.Catalog.GetString ("AddBOT");
		this.hbox1.Add (this.Addbot);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.Addbot]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w8.Position = 4;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.dltime = new global::Gtk.Entry ();
		this.dltime.CanFocus = true;
		this.dltime.Name = "dltime";
		this.dltime.IsEditable = true;
		this.dltime.InvisibleChar = '●';
		this.hbox2.Add (this.dltime);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.dltime]));
		w9.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.dltimeset = new global::Gtk.Button ();
		this.dltimeset.CanFocus = true;
		this.dltimeset.Name = "dltimeset";
		this.dltimeset.UseUnderline = true;
		this.dltimeset.Label = global::Mono.Unix.Catalog.GetString ("Set DL time");
		this.hbox2.Add (this.dltimeset);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.dltimeset]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w11.Position = 5;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Logging = new global::Gtk.Entry ();
		this.Logging.CanFocus = true;
		this.Logging.Name = "Logging";
		this.Logging.Text = global::Mono.Unix.Catalog.GetString ("All events will be shown here!");
		this.Logging.IsEditable = true;
		this.Logging.InvisibleChar = '●';
		this.hbox4.Add (this.Logging);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.Logging]));
		w12.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Events");
		this.hbox4.Add (this.label2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label2]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
		w14.Position = 6;
		w14.Expand = false;
		w14.Fill = false;
		this.hpaned1.Add (this.vbox1);
		global::Gtk.Paned.PanedChild w15 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vbox1]));
		w15.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.settingsloc = new global::Gtk.Entry ();
		this.settingsloc.CanFocus = true;
		this.settingsloc.Name = "settingsloc";
		this.settingsloc.Text = global::Mono.Unix.Catalog.GetString ("Settings.ini location (only if settings.ini already exists)");
		this.settingsloc.IsEditable = true;
		this.settingsloc.InvisibleChar = '●';
		this.hbox3.Add (this.settingsloc);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.settingsloc]));
		w16.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.OpenSettings = new global::Gtk.Button ();
		this.OpenSettings.CanFocus = true;
		this.OpenSettings.Name = "OpenSettings";
		this.OpenSettings.UseUnderline = true;
		this.OpenSettings.Label = global::Mono.Unix.Catalog.GetString ("Open Settings");
		this.hbox3.Add (this.OpenSettings);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.OpenSettings]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.createsettingfile = new global::Gtk.Button ();
		this.createsettingfile.CanFocus = true;
		this.createsettingfile.Name = "createsettingfile";
		this.createsettingfile.UseUnderline = true;
		this.createsettingfile.Label = global::Mono.Unix.Catalog.GetString ("Create Settings.ini");
		this.vbox2.Add (this.createsettingfile);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.createsettingfile]));
		w19.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.Save = new global::Gtk.Button ();
		this.Save.CanFocus = true;
		this.Save.Name = "Save";
		this.Save.UseUnderline = true;
		this.Save.Label = global::Mono.Unix.Catalog.GetString ("Save");
		this.vbox2.Add (this.Save);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.Save]));
		w20.Position = 2;
		this.hpaned1.Add (this.vbox2);
		this.GtkAlignment.Add (this.hpaned1);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel5 = new global::Gtk.Label ();
		this.GtkLabel5.Name = "GtkLabel5";
		this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Anime Subscription</b>");
		this.GtkLabel5.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel5;
		this.Add (this.frame1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultHeight = 519;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.addanime.Clicked += new global::System.EventHandler (this.AddToSub);
		this.dltimeset.Clicked += new global::System.EventHandler (this.OnDltimesetClicked);
		this.OpenSettings.Clicked += new global::System.EventHandler (this.OnOpenSettingsClicked);
		this.createsettingfile.Clicked += new global::System.EventHandler (this.OnCreatesettingfileClicked);
		this.Save.Clicked += new global::System.EventHandler (this.OnSaveClicked);
	}
}
